services:
  - type: web
    name: esgi-cloud-exam-29124
    region: frankfurt
    plan: free
    runtime: node
    repo:  https://github.com/rimey2/exam_cloud_esgi.git
    branch: master
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: base_exam
          property: connectionString

databases:
  - name: base_exam
    region: frankfurt
    plan: free
    databaseName: cloud
    user: cloud